Portflio task
Athaliah8/Portflio_Setup pull request #1
Opened 2022-10-28 08:53 UTC by Athaliah8

##In This repo

[ ] Added Linters
[ ] Added Html and Css file
[ ] Added gitflow
[ ]Added linter error file
[ ]Added images folder

2022-10-28 09:27 UTC, ha-manel reviewed
# STATUS: INVALID 🔴 
Hi @Athaliah8 
I'm sure you put a lot of effort into this project but this PR is invalid because you have linter errors😓 

![image](https://user-images.githubusercontent.com/50721479/198554167-8a30542c-729a-44fd-9b8a-22b24a263a34.png)

Kindly fix the issue and submit the PR for review again 👍 
Best of luck!

------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-28 14:18 UTC, Nyame-Wolf requested changes
# STATUS: REQUIRED CHANGES :recycle: 

Hi<STUDENT NAME> :wave: 

Your project page is looking fantastic so far :star_struck: ! 

However, there is still some room for improvement, that can help you have better code and make your project professional :sunglasses: 

![](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)

## Highlights :sparkles:

- Great work using the right GitHub Flow :100: 
- Linters are passing.

Congrats on your work so far! :clap:  

## Required Changes ♻️

There are some issues that you still need to work on to go to the next project, but you are almost there! 
_For more information, check the comments under the review :arrow_down:_

## Optional suggestions :ballot_box_with_check: 

_Every comment with the **[OPTIONAL]** prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can improve the quality of your code :100:_

Happy coding and keep it up! :raised_hands: 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
  Please, remember to tag me **@Nyame-Wolf**  in your question so I can receive the notification.

  **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------

  _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

2022-10-28 14:18 UTC, Nyame-Wolf commented on Images/index.html
> + <link rel="stylesheet" href="style.css">
Kindly fix the path to this css file. Currently they do not show the styles you implemented. 
This is your project currently.
<img width="1002" alt="Screenshot 2022-10-28 at 17 02 10" src="https://user-images.githubusercontent.com/48546992/198633945-40b0b424-b165-490d-986f-5702b19d4310.png">


This is the figma template
<img width="369" alt="Screenshot 2022-10-28 at 11 23 07" src="https://user-images.githubusercontent.com/48546992/198633084-e4f18421-6c1a-4d9d-8504-296c3dbe9ff6.png">

I suggest you either move the index.html to the root folder or fix the path.

2022-10-28 14:18 UTC, Nyame-Wolf commented on Images/index.html
> +<image src="./logo.svg" width="Hug (76px)" >
This should be a link tag `<a>` 
This is for three reasons: convention, semantics, and user experience(UX). [Check this link](https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page) for more info.

2022-10-28 14:18 UTC, Nyame-Wolf commented on Images/index.html
> +<h2>LET'S CONNECT</h2>
Please fix this to be a link `<a>`. By its a color, you can see that its blue. This should redirect people visiting your page to a contact form or your socials.

2022-10-28 14:18 UTC, Nyame-Wolf commented on Images/index.html
> + <section id="Main_Content">
This section should have background images as shown in the figma design.
<img width="369" alt="Screenshot 2022-10-28 at 11 23 07" src="https://user-images.githubusercontent.com/48546992/198638998-9f6fad3b-3256-4bd4-ac43-6ed2be5e1c1b.png">

 Its a requirement to pass this milestone.

2022-10-29 14:11 UTC, emmiiorji requested changes
Hi @Athaliah8, 

# Status: Changes Required ♻️

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Good Highlights✔

- Linter checks are passing
- Good commit messages
- Adherence to GitHub flow


 ## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-29 14:11 UTC, emmiiorji commented on index.html
> +      background-color: lightblue;
As requested by the previous reviewer, kindly avoid the use of inline styling. External styles make for more reusable styles.

2022-10-29 14:11 UTC, emmiiorji commented on style.css
> +}
Good job at adding the background image as requested by the previous reviewer. Kindly modify the section to follow the design template by sticking to font sizes and colours.

Your design:
![image](https://user-images.githubusercontent.com/20554583/198835830-ee02005c-817f-4866-93f6-9d80620201f8.png)

Figma design:
![image](https://user-images.githubusercontent.com/20554583/198835852-949aaa31-46d2-479d-81d6-d768fd4a6e61.png)

Note that:

- The text of the intro text does not overlap the background image
- The headline text is bolder than you have it
- There are some missing social icons in your design
- The LET'S CONNECT text together with the social icons are vertically aligned with the intro text and headline text.

2022-11-01 10:39 UTC, nedjwab approved these changes
# 🟢 Project Approved! 🏆

## Hi @Athaliah8  👋

Your project is complete! ✔️ 🏁

Your code was very professional 💯

There is nothing else to say other than... _it's time to merge it_ :shipit:
Congratulations! 🎉

 
## Highlights 🌟

- ✔️ Descriptive commmit messsages
- ✔️ Descriptive PR description
- ✔️ No linter Errors
- The code is top-notch! 💯 and have a huge potential.

Cheers and Happy coding!👏👏👏

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.


_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-02 22:16 UTC, merged